// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// BTFft
NumericVector BTFft(int m, int n, List interval, NumericVector z, NumericVector psi);
RcppExport SEXP isoph_BTFft(SEXP mSEXP, SEXP nSEXP, SEXP intervalSEXP, SEXP zSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< List >::type interval(intervalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type psi(psiSEXP);
    __result = Rcpp::wrap(BTFft(m, n, interval, z, psi));
    return __result;
END_RCPP
}
